# Generated by Django 3.2.5 on 2021-07-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_powtonn_powtoon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
