# Generated by Django 3.2.5 on 2021-07-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='PermissionGroup',
        ),
    ]
