# Generated by Django 3.2.5 on 2021-07-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_group_permissiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.permissiongroup'),
        ),
    ]
