# Generated by Django 3.2.5 on 2021-07-06 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.permissiongroup'),
        ),
    ]
