# Generated by Django 3.2.5 on 2021-07-20 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powtoons', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='PowtoonShared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powtoon.powtoon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='powtoon',
            name='shared_with',
            field=models.ManyToManyField(through='powtoon.PowtoonShared', to='user.User'),
        ),
    ]
